# Part 1

In [3]:
import numpy as np

In [31]:
class Board:
    def __init__(self):
        self.board = np.zeros((5,5), dtype=int)
        self.marked = np.zeros((5,5))

    def read_from_lines(self, lines):
        for i in range(5):
            line_entries = [int(entry) for entry in lines[i].split(' ') if entry != '']
            self.board[i] = line_entries
    
    def check_called_number(self, called_number):
        if called_number in self.board:
            indices = np.where(self.board == called_number)
            self.marked[indices[0], indices[1]] = 1

    def check_win(self):
        return self.marked.all(axis=0).any() or self.marked.all(axis=1).any()

    def calculate_score(self, called_number):
        return (self.board * (self.marked==0)).sum() * called_number

In [41]:
def read_board(lines):
    board = np.zeros((5,5), dtype=int)
    for i in range(5):
        line_entries = [int(entry) for entry in lines[i].split(' ') if entry != '']
        board[i] = line_entries
    return board

def find_first_winner(called_numbers, boards):
    for called_number in called_numbers:
        for j in range(len(boards)):
            boards[j].check_called_number(called_number)
            if boards[j].check_win():
                print(f"Board {j+1} won!")
                print(boards[j].marked)
                return j, called_number

def part1(file_name):
    with open(file_name, 'r') as f:
        lines = [entry.strip() for entry in f.readlines()]
    
    called_numbers = [int(entry) for entry in lines[0].split(',')]
    print(called_numbers)

    number_of_boards = (len(lines)-1)//6
    print(number_of_boards)
    boards = dict()
    for j in range(number_of_boards):
        boards[j] = Board()
        boards[j].read_from_lines(lines[(2 + j*6):(2+5+(j+1)*6)])
    #print([board.board for board in boards.values()])

    winner_index, called_number = find_first_winner(called_numbers, boards)    
    print('score', boards[winner_index].calculate_score(called_number))

In [42]:
part1('example.txt')

[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
3
Board 3 won!
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]]
score 4512


In [43]:
part1('input.txt')

[90, 4, 2, 96, 46, 1, 62, 97, 3, 52, 7, 35, 50, 28, 31, 37, 74, 26, 59, 53, 82, 47, 83, 80, 19, 40, 68, 95, 34, 55, 54, 73, 12, 78, 30, 63, 57, 93, 72, 77, 56, 91, 23, 67, 64, 79, 85, 84, 76, 10, 58, 0, 29, 13, 94, 20, 32, 25, 11, 38, 89, 21, 98, 92, 42, 27, 14, 99, 24, 75, 86, 51, 22, 48, 9, 33, 49, 18, 70, 8, 87, 61, 39, 16, 66, 71, 5, 69, 15, 43, 88, 45, 6, 81, 60, 36, 44, 17, 41, 65]
100
Board 23 won!
[[1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 0.]]
score 8136


# Part 2

In [47]:
def find_last_winner(called_numbers, boards):
    winners = []
    winner_call = 0
    for called_number in called_numbers:
        for j in range(len(boards)):
            if j not in winners:
                boards[j].check_called_number(called_number)
                if boards[j].check_win():
                    winners.append(j)
                    print(f"Board {j+1} won!")
                    winner_call = called_number
    return winners[-1], winner_call

def part2(file_name):
    with open(file_name, 'r') as f:
        lines = [entry.strip() for entry in f.readlines()]
    
    called_numbers = [int(entry) for entry in lines[0].split(',')]
    print(called_numbers)

    number_of_boards = (len(lines)-1)//6
    print(number_of_boards)
    boards = dict()
    for j in range(number_of_boards):
        boards[j] = Board()
        boards[j].read_from_lines(lines[(2 + j*6):(2+5+(j+1)*6)])
    #print([board.board for board in boards.values()])

    winner_index, called_number = find_last_winner(called_numbers, boards)    
    print('score', boards[winner_index].calculate_score(called_number))

In [48]:
part2('example.txt')

[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]
3
Board 3 won!
Board 1 won!
Board 2 won!
score 1924


In [49]:
part2('input.txt')

[90, 4, 2, 96, 46, 1, 62, 97, 3, 52, 7, 35, 50, 28, 31, 37, 74, 26, 59, 53, 82, 47, 83, 80, 19, 40, 68, 95, 34, 55, 54, 73, 12, 78, 30, 63, 57, 93, 72, 77, 56, 91, 23, 67, 64, 79, 85, 84, 76, 10, 58, 0, 29, 13, 94, 20, 32, 25, 11, 38, 89, 21, 98, 92, 42, 27, 14, 99, 24, 75, 86, 51, 22, 48, 9, 33, 49, 18, 70, 8, 87, 61, 39, 16, 66, 71, 5, 69, 15, 43, 88, 45, 6, 81, 60, 36, 44, 17, 41, 65]
100
Board 23 won!
Board 83 won!
Board 72 won!
Board 99 won!
Board 33 won!
Board 15 won!
Board 7 won!
Board 10 won!
Board 42 won!
Board 36 won!
Board 73 won!
Board 94 won!
Board 17 won!
Board 21 won!
Board 31 won!
Board 66 won!
Board 67 won!
Board 71 won!
Board 82 won!
Board 43 won!
Board 16 won!
Board 32 won!
Board 40 won!
Board 22 won!
Board 52 won!
Board 24 won!
Board 79 won!
Board 3 won!
Board 20 won!
Board 41 won!
Board 63 won!
Board 80 won!
Board 1 won!
Board 13 won!
Board 25 won!
Board 46 won!
Board 69 won!
Board 89 won!
Board 37 won!
Board 54 won!
Board 56 won!
Board 100 won!
Board 51 won!
Board